In [13]:
import pandas as pd
import os

# Automatically detect any uploaded CSV file in the directory
files_in_dir = os.listdir('/content/')
csv_files = [f for f in files_in_dir if f.endswith('.csv')]

if csv_files:
    filename = csv_files[0]
    filepath = f'/content/{filename}'
    df = pd.read_csv(filepath)
    print(f"Successfully detected and loaded '{filename}'!")
    print(f"Dataset Shape: {df.shape}")
    display(df.head())
else:
    print("No CSV file found yet in /content/.")
    print("Please upload your file via the folder sidebar on the left and run this cell again!")
    print("Current directory contents:", files_in_dir)

Successfully detected and loaded 'retail_store_sales.csv'!
Dataset Shape: (12575, 11)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [16]:
print(df.describe())

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [18]:
df.shape

(12575, 11)

In [26]:
missing_count = df.isnull().sum()

missing_percentage = (missing_count / len(df)) * 100

print(missing_percentage.round(2))

Transaction ID       0.00
Customer ID          0.00
Category             0.00
Item                 9.65
Price Per Unit       4.84
Quantity             4.80
Total Spent          4.80
Payment Method       0.00
Location             0.00
Transaction Date     0.00
Discount Applied    33.39
dtype: float64

In [27]:
print(df[df["Item"].isnull()].head(10))

   Transaction ID Customer ID       Category Item  Price Per Unit  Quantity  \
5     TXN_7482416     CUST_09     Patisserie  NaN             NaN      10.0
7     TXN_1372952     CUST_21      Furniture  NaN            33.5       NaN
11    TXN_5422631     CUST_09  Milk Products  NaN             NaN       8.0
15    TXN_1809665     CUST_14      Beverages  NaN            24.5       NaN
17    TXN_9634894     CUST_15  Milk Products  NaN             NaN      10.0
19    TXN_4206593     CUST_01      Furniture  NaN            35.0       NaN
21    TXN_8685338     CUST_15  Milk Products  NaN             NaN       3.0
25    TXN_3481599     CUST_05      Furniture  NaN            39.5       NaN
32    TXN_1543244     CUST_20           Food  NaN             NaN       8.0
34    TXN_1621497     CUST_06     Patisserie  NaN            23.0       NaN

    Total Spent  Payment Method  Location Transaction Date Discount Applied
5         200.0     Credit Card    Online       2023-11-30              NaN
7           NaN  Digital Wallet  In-store       2024-04-02             True
11         52.0  Digital Wallet  In-store       2025-01-12             True
15          NaN     Credit Card  In-store       2022-05-11              NaN
17        275.0  Digital Wallet    Online       2022-04-17              NaN
19          NaN  Digital Wallet    Online       2025-01-13            False
21        105.0     Credit Card  In-store       2023-10-29              NaN
25          NaN            Cash    Online       2022-09-08            False
32        196.0     Credit Card    Online       2024-10-25             True
34          NaN            Cash  In-store       2023-02-18              NaN

In [28]:
print(df["Discount Applied"].value_counts(dropna=False))

Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

In [29]:
print(df.dtypes)

Transaction ID       object
Customer ID          object
Category             object
Item                 object
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method       object
Location             object
Transaction Date     object
Discount Applied     object
dtype: object

In [30]:
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"],
    errors="coerce"
)

print(df["Transaction Date"].dtype)

datetime64[ns]

In [31]:
print(df[df["Discount Applied"].isnull()].head(10))

   Transaction ID Customer ID                       Category          Item  \
3     TXN_9458126     CUST_06                      Beverages   Item_16_BEV
5     TXN_7482416     CUST_09                     Patisserie           NaN
14    TXN_2490363     CUST_09                  Milk Products  Item_16_MILK
15    TXN_1809665     CUST_14                      Beverages           NaN
17    TXN_9634894     CUST_15                  Milk Products           NaN
20    TXN_9939063     CUST_14                      Beverages    Item_7_BEV
21    TXN_8685338     CUST_15                  Milk Products           NaN
22    TXN_6547964     CUST_10  Electric household essentials    Item_4_EHE
33    TXN_1494700     CUST_12  Electric household essentials   Item_21_EHE
34    TXN_1621497     CUST_06                     Patisserie           NaN

    Price Per Unit  Quantity  Total Spent  Payment Method  Location  \
3             27.5       9.0        247.5     Credit Card    Online
5              NaN      10.0        200.0     Credit Card    Online
14            27.5       2.0         55.0  Digital Wallet    Online
15            24.5       NaN          NaN     Credit Card  In-store
17             NaN      10.0        275.0  Digital Wallet    Online
20            14.0       9.0        126.0  Digital Wallet  In-store
21             NaN       3.0        105.0     Credit Card  In-store
22             9.5       7.0         66.5            Cash  In-store
33            35.0       9.0        315.0     Credit Card  In-store
34            23.0       NaN          NaN            Cash  In-store

   Transaction Date Discount Applied
3        2022-05-07              NaN
5        2023-11-30              NaN
14       2022-05-22              NaN
15       2022-05-11              NaN
17       2022-04-17              NaN
20       2024-01-14              NaN
21       2023-10-29              NaN
22       2022-08-15              NaN
33       2024-03-07              NaN
34       2023-02-18              NaN

In [32]:
print(
    df.groupby("Discount Applied")["Total Spent"].mean()
)

Discount Applied
False    129.953330
True     130.491043
Name: Total Spent, dtype: float64

In [33]:
print(
    df[df["Discount Applied"].isnull()]["Payment Method"]
    .value_counts()
)

Payment Method
Cash              1473
Credit Card       1365
Digital Wallet    1361
Name: count, dtype: int64

In [34]:
print(
    df[df["Discount Applied"].isnull()]["Category"]
    .value_counts()
)

Category
Furniture                             570
Beverages                             551
Electric household essentials         541
Food                                  533
Patisserie                            521
Butchers                              511
Milk Products                         495
Computers and electric accessories    477
Name: count, dtype: int64

In [35]:
print(
    df.groupby("Category")["Discount Applied"]
    .apply(lambda x: x.isnull().mean() * 100)
    .round(2)
)

Category
Beverages                             35.16
Butchers                              32.59
Computers and electric accessories    30.62
Electric household essentials         34.00
Food                                  33.56
Furniture                             35.83
Milk Products                         31.25
Patisserie                            34.10
Name: Discount Applied, dtype: float64

In [36]:
print(
    df.groupby("Payment Method")["Discount Applied"]
    .apply(lambda x: x.isnull().mean() * 100)
    .round(2)
)

Payment Method
Cash              34.18
Credit Card       33.12
Digital Wallet    32.84
Name: Discount Applied, dtype: float64

In [37]:
print(df["Discount Applied"].value_counts(dropna=False))

Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

In [38]:
print(df["Discount Applied"].map(type).value_counts())

Discount Applied
<class 'bool'>     8376
<class 'float'>    4199
Name: count, dtype: int64

In [39]:
missing_items = df[df["Item"].isnull()]

print(missing_items[["Category", "Price Per Unit", "Quantity", "Total Spent"]].head(10))

         Category  Price Per Unit  Quantity  Total Spent
5      Patisserie             NaN      10.0        200.0
7       Furniture            33.5       NaN          NaN
11  Milk Products             NaN       8.0         52.0
15      Beverages            24.5       NaN          NaN
17  Milk Products             NaN      10.0        275.0
19      Furniture            35.0       NaN          NaN
21  Milk Products             NaN       3.0        105.0
25      Furniture            39.5       NaN          NaN
32           Food             NaN       8.0        196.0
34     Patisserie            23.0       NaN          NaN

In [40]:
print(
    df.groupby("Category")["Item"]
    .nunique()
)

Category
Beverages                             25
Butchers                              25
Computers and electric accessories    25
Electric household essentials         25
Food                                  25
Furniture                             25
Milk Products                         25
Patisserie                            25
Name: Item, dtype: int64

In [41]:
print(
    df[["Category", "Item", "Price Per Unit"]]
    .dropna()
    .drop_duplicates()
    .sort_values(["Category", "Price Per Unit"])
    .head(20)
    .to_string(index=False)
)

 Category        Item  Price Per Unit
Beverages  Item_1_BEV             5.0
Beverages  Item_2_BEV             6.5
Beverages  Item_3_BEV             8.0
Beverages  Item_4_BEV             9.5
Beverages  Item_5_BEV            11.0
Beverages  Item_6_BEV            12.5
Beverages  Item_7_BEV            14.0
Beverages  Item_8_BEV            15.5
Beverages  Item_9_BEV            17.0
Beverages Item_10_BEV            18.5
Beverages Item_11_BEV            20.0
Beverages Item_12_BEV            21.5
Beverages Item_13_BEV            23.0
Beverages Item_14_BEV            24.5
Beverages Item_15_BEV            26.0
Beverages Item_16_BEV            27.5
Beverages Item_17_BEV            29.0
Beverages Item_18_BEV            30.5
Beverages Item_19_BEV            32.0
Beverages Item_20_BEV            33.5

In [43]:
price_item_counts = (
    df.dropna(subset=["Category", "Item", "Price Per Unit"])
    .groupby(["Category", "Price Per Unit"])["Item"]
    .nunique()
)

print(price_item_counts[price_item_counts > 1])

Series([], Name: Item, dtype: int64)

In [44]:
missing_item_rows = df[df["Item"].isnull()]

print("Total missing items:", len(missing_item_rows))

print(
    "Missing items with category and price available:",
    missing_item_rows[["Category", "Price Per Unit"]].notnull().all(axis=1).sum()
)

Total missing items: 1213
Missing items with category and price available: 604

In [45]:
# Keep rows where the item, category, and price are available
known_items = df.dropna(
    subset=["Category", "Item", "Price Per Unit"]
)

# Create a lookup table using category and price
item_lookup = known_items.drop_duplicates(
    subset=["Category", "Price Per Unit"]
)[["Category", "Price Per Unit", "Item"]]

print(item_lookup.head(10))

         Category  Price Per Unit          Item
0      Patisserie            18.5   Item_10_PAT
1   Milk Products            29.0  Item_17_MILK
2        Butchers            21.5   Item_12_BUT
3       Beverages            27.5   Item_16_BEV
4            Food            12.5   Item_6_FOOD
6            Food             5.0   Item_1_FOOD
8       Furniture            27.5   Item_16_FUR
9        Butchers            36.5   Item_22_BUT
10       Butchers             8.0    Item_3_BUT
12           Food             6.5   Item_2_FOOD

In [46]:
item_counts = (
    df.dropna(subset=["Category", "Item", "Price Per Unit"])
    .groupby(["Category", "Price Per Unit"])["Item"]
    .nunique()
)

print(item_counts.max())

1

In [47]:
df["Item Cleaned"] = df["Item"]

In [48]:
item_lookup = (
    df.dropna(subset=["Category", "Item", "Price Per Unit"])
    .drop_duplicates(subset=["Category", "Price Per Unit"])
    .set_index(["Category", "Price Per Unit"])["Item"]
)

In [49]:
missing_item = df["Item Cleaned"].isnull()

In [50]:
df.loc[missing_item, "Item Cleaned"] = pd.MultiIndex.from_frame(
    df.loc[missing_item, ["Category", "Price Per Unit"]]
).map(item_lookup)

In [51]:
print("Missing items before:", df["Item"].isnull().sum())

print("Missing items after:", df["Item Cleaned"].isnull().sum())

Missing items before: 1213
Missing items after: 609

In [52]:
print(
    df.loc[
        df["Item"].isnull() & df["Item Cleaned"].notnull(),
        ["Category", "Price Per Unit", "Item Cleaned"]
    ].head(10)
)

                               Category  Price Per Unit Item Cleaned
7                             Furniture            33.5  Item_20_FUR
15                            Beverages            24.5  Item_14_BEV
19                            Furniture            35.0  Item_21_FUR
25                            Furniture            39.5  Item_24_FUR
34                           Patisserie            23.0  Item_13_PAT
83                           Patisserie            15.5   Item_8_PAT
112  Computers and electric accessories            20.0  Item_11_CEA
114                           Beverages            39.5  Item_24_BEV
118  Computers and electric accessories            27.5  Item_16_CEA
138                           Furniture            35.0  Item_21_FUR

In [53]:
print(
    df.loc[
        df["Item Cleaned"].isnull(),
        ["Category", "Price Per Unit", "Quantity", "Total Spent"]
    ].head(10)
)

                          Category  Price Per Unit  Quantity  Total Spent
5                       Patisserie             NaN      10.0        200.0
11                   Milk Products             NaN       8.0         52.0
17                   Milk Products             NaN      10.0        275.0
21                   Milk Products             NaN       3.0        105.0
32                            Food             NaN       8.0        196.0
127                       Butchers             NaN      10.0        275.0
159                       Butchers             NaN       9.0        126.0
216                     Patisserie             NaN       8.0         40.0
247  Electric household essentials             NaN       7.0        150.5
271                  Milk Products             NaN       9.0         99.0

In [54]:
missing_price = (
    df["Price Per Unit"].isnull()
    & df["Quantity"].notnull()
    & df["Total Spent"].notnull()
)

df.loc[missing_price, "Calculated Price"] = (
    df.loc[missing_price, "Total Spent"]
    / df.loc[missing_price, "Quantity"]
)

print(
    df.loc[
        missing_price,
        ["Category", "Quantity", "Total Spent", "Calculated Price"]
    ].head(10)
)

                          Category  Quantity  Total Spent  Calculated Price
5                       Patisserie      10.0        200.0              20.0
11                   Milk Products       8.0         52.0               6.5
17                   Milk Products      10.0        275.0              27.5
21                   Milk Products       3.0        105.0              35.0
32                            Food       8.0        196.0              24.5
127                       Butchers      10.0        275.0              27.5
159                       Butchers       9.0        126.0              14.0
216                     Patisserie       8.0         40.0               5.0
247  Electric household essentials       7.0        150.5              21.5
271                  Milk Products       9.0         99.0              11.0

In [55]:
missing_item_with_price = (
    df["Item Cleaned"].isnull()
    & df["Calculated Price"].notnull()
)

calculated_matches = pd.MultiIndex.from_arrays([
    df.loc[missing_item_with_price, "Category"],
    df.loc[missing_item_with_price, "Calculated Price"]
]).map(item_lookup)

df.loc[missing_item_with_price, "Item Cleaned"] = calculated_matches

print("Missing items remaining:", df["Item Cleaned"].isnull().sum())

Missing items remaining: 0

In [56]:
print(
    df.loc[
        df["Item"].isnull(),
        ["Category", "Price Per Unit", "Quantity",
         "Total Spent", "Calculated Price", "Item Cleaned"]
    ].head(10).to_string(index=False)
)

     Category  Price Per Unit  Quantity  Total Spent  Calculated Price Item Cleaned
   Patisserie             NaN      10.0        200.0              20.0  Item_11_PAT
    Furniture            33.5       NaN          NaN               NaN  Item_20_FUR
Milk Products             NaN       8.0         52.0               6.5  Item_2_MILK
    Beverages            24.5       NaN          NaN               NaN  Item_14_BEV
Milk Products             NaN      10.0        275.0              27.5 Item_16_MILK
    Furniture            35.0       NaN          NaN               NaN  Item_21_FUR
Milk Products             NaN       3.0        105.0              35.0 Item_21_MILK
    Furniture            39.5       NaN          NaN               NaN  Item_24_FUR
         Food             NaN       8.0        196.0              24.5 Item_14_FOOD
   Patisserie            23.0       NaN          NaN               NaN  Item_13_PAT

In [57]:
complete_rows = df[
    ["Price Per Unit", "Quantity", "Total Spent"]
].notnull().all(axis=1)

calculated_total = (
    df.loc[complete_rows, "Price Per Unit"]
    * df.loc[complete_rows, "Quantity"]
)

actual_total = df.loc[complete_rows, "Total Spent"]

print("Rows checked:", len(calculated_total))

print(
    "Rows where totals do not match:",
    ((calculated_total - actual_total).abs() > 0.01).sum()
)

Rows checked: 11362
Rows where totals do not match: 0

In [58]:
missing_price = (
    df["Price Per Unit"].isnull()
    & df["Quantity"].notnull()
    & df["Total Spent"].notnull()
)

print("Missing prices that can be calculated:", missing_price.sum())

Missing prices that can be calculated: 609

In [60]:
# Copy the original price column
df["Price Cleaned"] = df["Price Per Unit"]

# Find rows where price is missing but quantity and total are available
missing_price = (
    df["Price Cleaned"].isnull()
    & df["Quantity"].notnull()
    & df["Total Spent"].notnull()
)

# Calculate the missing prices
df.loc[missing_price, "Price Cleaned"] = (
    df.loc[missing_price, "Total Spent"]
    / df.loc[missing_price, "Quantity"]
)

# Check remaining missing prices
print("Missing prices remaining:", df["Price Cleaned"].isnull().sum())

Missing prices remaining: 0

In [61]:
print("Missing quantities:", df["Quantity"].isnull().sum())

print("\nExamples of rows with missing quantities:")

print(
    df.loc[
        df["Quantity"].isnull(),
        ["Category", "Item", "Price Per Unit",
         "Total Spent", "Price Cleaned"]
    ].head(10).to_string(index=False)
)

Missing quantities: 604

Examples of rows with missing quantities:
                          Category Item  Price Per Unit  Total Spent  Price Cleaned
                         Furniture  NaN            33.5          NaN           33.5
                         Beverages  NaN            24.5          NaN           24.5
                         Furniture  NaN            35.0          NaN           35.0
                         Furniture  NaN            39.5          NaN           39.5
                        Patisserie  NaN            23.0          NaN           23.0
                        Patisserie  NaN            15.5          NaN           15.5
Computers and electric accessories  NaN            20.0          NaN           20.0
                         Beverages  NaN            39.5          NaN           39.5
Computers and electric accessories  NaN            27.5          NaN           27.5
                         Furniture  NaN            35.0          NaN           35.0

In [62]:
# Find rows where quantity is missing but total spent is available
missing_quantity_check = (
    df["Quantity"].isnull()
    & df["Total Spent"].notnull()
    & df["Price Cleaned"].notnull()
)

print(
    "Missing quantities that can be calculated:",
    missing_quantity_check.sum()
)

Missing quantities that can be calculated: 0

In [63]:
print("Missing Total Spent:", df["Total Spent"].isnull().sum())

missing_total_check = (
    df["Total Spent"].isnull()
    & df["Price Cleaned"].notnull()
    & df["Quantity"].notnull()
)

print(
    "Missing totals that can be calculated:",
    missing_total_check.sum()
)

Missing Total Spent: 604
Missing totals that can be calculated: 0

In [64]:
both_missing = (
    df["Quantity"].isnull()
    & df["Total Spent"].isnull()
)

print("Rows where both are missing:", both_missing.sum())

Rows where both are missing: 604

In [65]:
print("Missing discounts:", df["Discount Applied"].isnull().sum())

print("\nDiscount values:")
print(df["Discount Applied"].value_counts(dropna=False))

Missing discounts: 4199

Discount values:
Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

In [66]:
discount_by_payment = pd.crosstab(
    df["Payment Method"],
    df["Discount Applied"],
    normalize="index"
) * 100

print(discount_by_payment.round(2))

Discount Applied  False  True
Payment Method
Cash              48.57  51.43
Credit Card       49.31  50.69
Digital Wallet    51.02  48.98

In [67]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().mean() * 100).round(2)
})

print(missing_summary)

                  Missing Count  Missing Percentage
Transaction ID                0                0.00
Customer ID                   0                0.00
Category                      0                0.00
Item                       1213                9.65
Price Per Unit              609                4.84
Quantity                    604                4.80
Total Spent                 604                4.80
Payment Method                0                0.00
Location                      0                0.00
Transaction Date              0                0.00
Discount Applied           4199               33.39
Item Cleaned                  0                0.00
Calculated Price          11966               95.16
Price Cleaned                 0                0.00

In [68]:
print(
    "Missing cleaned prices:",
    df["Price Cleaned"].isnull().sum()
)

print(
    "Zero or negative cleaned prices:",
    (df["Price Cleaned"] <= 0).sum()
)

Missing cleaned prices: 0
Zero or negative cleaned prices: 0

In [69]:
# Check for missing item names
print(
    "Missing cleaned items:",
    df["Item Cleaned"].isnull().sum()
)

# Check whether each item name matches its category
item_category_counts = (
    df.dropna(subset=["Item Cleaned", "Category"])
    .groupby("Item Cleaned")["Category"]
    .nunique()
)

print(
    "Items linked to multiple categories:",
    (item_category_counts > 1).sum()
)

Missing cleaned items: 0
Items linked to multiple categories: 0

In [70]:
print(
    "Zero or negative totals:",
    (df["Total Spent"] <= 0).sum()
)

print(
    "Negative quantities:",
    (df["Quantity"] < 0).sum()
)

Zero or negative totals: 0
Negative quantities: 0

In [71]:
print("Exact duplicate rows:", df.duplicated().sum())

print(
    "Duplicate Transaction IDs:",
    df["Transaction ID"].duplicated().sum()
)

Exact duplicate rows: 0
Duplicate Transaction IDs: 0

In [72]:
print("Earliest transaction date:", df["Transaction Date"].min())

print("Latest transaction date:", df["Transaction Date"].max())

print("Missing transaction dates:", df["Transaction Date"].isnull().sum())

Earliest transaction date: 2022-01-01 00:00:00
Latest transaction date: 2025-01-18 00:00:00
Missing transaction dates: 0

In [73]:
print(df["Transaction Date"].dtype)

datetime64[ns]

In [74]:
# Create a new column containing the month and year
df["Month"] = df["Transaction Date"].dt.to_period("M")

# Check the result
print(df[["Transaction Date", "Month"]].head(10))

  Transaction Date    Month
0       2024-04-08  2024-04
1       2023-07-23  2023-07
2       2022-10-05  2022-10
3       2022-05-07  2022-05
4       2022-10-02  2022-10
5       2023-11-30  2023-11
6       2023-06-10  2023-06
7       2024-04-02  2024-04
8       2023-04-26  2023-04
9       2024-03-14  2024-03

In [75]:
# Calculate revenue using cleaned prices
df["Revenue"] = df["Price Cleaned"] * df["Quantity"]

# Display the results
print(
    df[["Price Cleaned", "Quantity", "Revenue"]].head(10)
)

   Price Cleaned  Quantity  Revenue
0           18.5      10.0    185.0
1           29.0       9.0    261.0
2           21.5       2.0     43.0
3           27.5       9.0    247.5
4           12.5       7.0     87.5
5           20.0      10.0    200.0
6            5.0       8.0     40.0
7           33.5       NaN      NaN
8           27.5       1.0     27.5
9           36.5       3.0    109.5

In [76]:
print("Missing revenue rows:", df["Revenue"].isnull().sum())

print("Available total revenue:", df["Revenue"].sum())

print("Rows with available revenue:", df["Revenue"].notnull().sum())

Missing revenue rows: 604
Available total revenue: 1552071.0
Rows with available revenue: 11971

In [77]:
# Calculate total available revenue for each category
category_revenue = (
    df.groupby("Category")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

print(category_revenue)

Category
Butchers                              208118.0
Electric household essentials         203813.5
Beverages                             197047.5
Furniture                             195310.0
Food                                  194812.0
Computers and electric accessories    190692.5
Patisserie                            182165.5
Milk Products                         180112.0
Name: Revenue, dtype: float64

In [78]:
# Calculate available revenue for each month
monthly_revenue = (
    df.groupby("Month")["Revenue"]
    .sum()
    .sort_index()
)

print(monthly_revenue)

Month
2022-01    52911.5
2022-02    43325.5
2022-03    40996.0
2022-04    40442.0
2022-05    40347.5
2022-06    42576.0
2022-07    44471.5
2022-08    41333.5
2022-09    46113.5
2022-10    38355.0
2022-11    41256.5
2022-12    38201.0
2023-01    48052.5
2023-02    39214.5
2023-03    38534.5
2023-04    38905.5
2023-05    40480.5
2023-06    42474.0
2023-07    45632.5
2023-08    38592.0
2023-09    41069.0
2023-10    38322.0
2023-11    37014.0
2023-12    43021.0
2024-01    47908.5
2024-02    37145.0
2024-03    42861.5
2024-04    46271.0
2024-05    43766.5
2024-06    44721.0
2024-07    41405.0
2024-08    43362.0
2024-09    42161.5
2024-10    42736.5
2024-11    44076.0
2024-12    48466.5
2025-01    25548.5
Freq: M, Name: Revenue, dtype: float64

In [79]:
# Find the month with the highest available revenue
highest_month = monthly_revenue.idxmax()
highest_revenue = monthly_revenue.max()

# Find the month with the lowest available revenue
lowest_month = monthly_revenue.idxmin()
lowest_revenue = monthly_revenue.min()

print("Highest revenue month:", highest_month)
print("Highest revenue:", highest_revenue)

print("Lowest revenue month:", lowest_month)
print("Lowest revenue:", lowest_revenue)

Highest revenue month: 2022-01
Highest revenue: 52911.5
Lowest revenue month: 2025-01
Lowest revenue: 25548.5

In [80]:
# Calculate available revenue for each item
item_revenue = (
    df.groupby("Item Cleaned")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

# Display the top 10 items
print(item_revenue.head(10))

Item Cleaned
Item_25_FUR     25625.0
Item_25_EHE     25502.0
Item_25_BUT     22427.0
Item_24_FUR     22080.5
Item_25_FOOD    21771.0
Item_22_BUT     21462.0
Item_23_BUT     20596.0
Item_19_MILK    20448.0
Item_23_EHE     20178.0
Item_23_PAT     19684.0
Name: Revenue, dtype: float64

In [81]:
category_summary = (
    df.groupby("Category")
    .agg(
        Transaction_Count=("Transaction ID", "count"),
        Total_Revenue=("Revenue", "sum")
    )
    .sort_values("Total_Revenue", ascending=False)
)

print(category_summary)

                                    Transaction_Count  Total_Revenue
Category
Butchers                                         1568       208118.0
Electric household essentials                    1591       203813.5
Beverages                                        1567       197047.5
Furniture                                        1591       195310.0
Food                                             1588       194812.0
Computers and electric accessories               1558       190692.5
Patisserie                                       1528       182165.5
Milk Products                                    1584       180112.0

In [82]:
category_summary = (
    df.groupby("Category")
    .agg(
        Transaction_Count=("Transaction ID", "count"),
        Total_Revenue=("Revenue", "sum"),
        Average_Revenue=("Revenue", "mean")
    )
    .sort_values("Average_Revenue", ascending=False)
)

print(category_summary.round(2))

                                    Transaction_Count  Total_Revenue  \
Category
Butchers                                         1568       208118.0
Electric household essentials                    1591       203813.5
Beverages                                        1567       197047.5
Food                                             1588       194812.0
Computers and electric accessories               1558       190692.5
Furniture                                        1591       195310.0
Patisserie                                       1528       182165.5
Milk Products                                    1584       180112.0

                                    Average_Revenue
Category
Butchers                                     139.12
Electric household essentials                134.44
Beverages                                    131.72
Food                                         129.27
Computers and electric accessories           129.11
Furniture                                    128.07
Patisserie                                   126.42
Milk Products                                119.04

In [83]:
category_quantity = (
    df.groupby("Category")["Quantity"]
    .sum()
    .sort_values(ascending=False)
)

print(category_quantity)

Category
Furniture                             8462.0
Food                                  8387.0
Beverages                             8358.0
Milk Products                         8339.0
Electric household essentials         8309.0
Computers and electric accessories    8272.0
Butchers                              8206.0
Patisserie                            7943.0
Name: Quantity, dtype: float64

In [84]:
category_analysis = (
    df.groupby("Category")
    .agg(
        Total_Revenue=("Revenue", "sum"),
        Total_Quantity=("Quantity", "sum"),
        Average_Revenue=("Revenue", "mean")
    )
    .sort_values("Total_Revenue", ascending=False)
)

print(category_analysis.round(2))

                                    Total_Revenue  Total_Quantity  \
Category
Butchers                                 208118.0          8206.0
Electric household essentials            203813.5          8309.0
Beverages                                197047.5          8358.0
Furniture                                195310.0          8462.0
Food                                     194812.0          8387.0
Computers and electric accessories       190692.5          8272.0
Patisserie                               182165.5          7943.0
Milk Products                            180112.0          8339.0

                                    Average_Revenue
Category
Butchers                                     139.12
Electric household essentials                134.44
Beverages                                    131.72
Furniture                                    128.07
Food                                         129.27
Computers and electric accessories           129.11
Patisserie                                   126.42
Milk Products                                119.04

In [85]:

# FINAL DATA QUALITY CHECK

print("Dataset shape:", df.shape)

print("\nMissing values in important columns:")
print(df[[
    "Item Cleaned",
    "Price Cleaned",
    "Quantity",
    "Total Spent",
    "Discount Applied"
]].isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())
print("Duplicate transaction IDs:",
      df["Transaction ID"].duplicated().sum())

print("\nNegative quantities:",
      (df["Quantity"] < 0).sum())

print("\nNon-positive totals:",
      (df["Total Spent"] <= 0).sum())

Dataset shape: (12575, 16)

Missing values in important columns:
Item Cleaned           0
Price Cleaned          0
Quantity             604
Total Spent          604
Discount Applied    4199
dtype: int64

Duplicate rows: 0
Duplicate transaction IDs: 0

Negative quantities: 0

Non-positive totals: 0

In [86]:

import pandas as pd

# Ensure the date column has the correct format
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"], errors="coerce"
)

# Create month and revenue columns
df["Month"] = (
    df["Transaction Date"]
    .dt.to_period("M")
    .astype("string")
)

df["Revenue"] = (
    df["Price Cleaned"] * df["Quantity"]
)

# Create a final dataset using cleaned values
df_final = pd.DataFrame({
    "Transaction ID": df["Transaction ID"],
    "Customer ID": df["Customer ID"],
    "Category": df["Category"],
    "Item": df["Item Cleaned"],
    "Price Per Unit": df["Price Cleaned"],
    "Quantity": df["Quantity"],
    "Total Spent": df["Total Spent"],
    "Revenue": df["Revenue"],
    "Payment Method": df["Payment Method"],
    "Location": df["Location"],
    "Transaction Date": df["Transaction Date"],
    "Month": df["Month"],
    "Discount Applied": df["Discount Applied"]
})

print("Final dataset shape:", df_final.shape)
df_final.head()

Final dataset shape: (12575, 13)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Revenue,Payment Method,Location,Transaction Date,Month,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,185.0,Digital Wallet,Online,2024-04-08,2024-04,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,261.0,Digital Wallet,Online,2023-07-23,2023-07,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,43.0,Credit Card,Online,2022-10-05,2022-10,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,247.5,Credit Card,Online,2022-05-07,2022-05,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,87.5,Digital Wallet,Online,2022-10-02,2022-10,False

In [87]:

# Save the final dataset as a CSV file
output_file = "Retail_Store_Sales_Cleaned.csv"

df_final.to_csv(output_file, index=False)

print("File saved successfully:", output_file)
print("Rows exported:", len(df_final))
print("Columns exported:", len(df_final.columns))

# Download the CSV from Google Colab
from google.colab import files
files.download(output_file)

File saved successfully: Retail_Store_Sales_Cleaned.csv
Rows exported: 12575
Columns exported: 13